FROM golang:1.26.3-alpine AS notifier-build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /notifier ./cmd/notifier

FROM alpine:3.20
COPY --from=notifier-build /notifier /notifier
ENTRYPOINT ["/notifier"]
